apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: flask-app
        image: jk0909/flask-mysql:f6021c330e7885dd8b2d6cb44603a81e6c702497
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_DATABASE_HOST
          value: db
      initContainers:
      - name: wait-for-db
        image: busybox
        command:
          [
            "sh",
            "-c",
            "until nc -z db 3306; do echo waiting for db; sleep 3; done;"
          ]

